students/AustinScara/README.md

made my own directory

---

README.rst

Greetings!  Here is my README.rst file with a small bit of text.

Added a README.rst file

---

kathleen/README.rst

testing      testing      testing

my first pull request

---

students/README.rst

adding readme file and creating pull request.

added readme file

---

students/cheryl/README.rst

made a readme in my own dir

---

students/AustinScara/FizzBuzz.py
students/AustinScara/grid_printer.py

grid file yey

---

students/gabriel_meringolo/session_02/series.py

I added an if statement to check if being ran directly, if so will run assert statements

Added main block

---

students/maxmaccamy/session02/grid_printer.py

Contains two print_grid functions that take arguments used to draw a simple grid pattern.

Updated grid_printer 

---

students/ryan_morin/session_02/fizz_buzz.py
students/ryan_morin/session_02/series.py

Fizz_Buzz and Series pull

---

students/JosephC/Session_02/FizzBuzz.py
students/JosephC/Session_02/grid_printer_v2.py
students/JosephC/Session_02/grid_printer_v3.py
students/JosephC/Session_02/series.py
students/JosephC/grid_printer.py

Sunday pull request

---

Solutions/session02/FizzBizz.py

This is my first pull request.  An attempt to submit my FizzBizz solution

My FizzBizz solution

---

students/martypitts/session02/fizbuzz.py
students/martypitts/session02/grid_printer.py
students/martypitts/session02/grid_printer_size.py
students/martypitts/session02/series.py

session2 checkin

---

students/maxmaccamy/session02/fizzbuzz.py
students/maxmaccamy/session02/series.py

Finished FizzBuzz example. Took me forever to realize that I was looking at the wrong branch for this pull request.

FizzBuzz example

---

students/ryan_morin/session_02/fizz_buzz.py
students/ryan_morin/session_02/series.py
students/ryan_morin/session_03/mailroom.py
students/ryan_morin/session_03/rot13.py

Rot13 complete but Mailroom is still being fine tuned

Session3 Homework ROT13 and Mailroom

---

students/gabriel_meringolo/session_02/boolLab.py
students/gabriel_meringolo/session_03/mail_menu.py
students/gabriel_meringolo/session_03/mailroom.py
students/gabriel_meringolo/session_03/rot13.py
students/gabriel_meringolo/session_04/dict_lab.py
students/gabriel_meringolo/session_04/file_lab.py
students/gabriel_meringolo/session_04/trigram.py

I got the rot13 function to work with the translate method but the asserts won't work, they are throwing a flag even when its working properly. I'm not sure why. Any insight would be appreciated. Thanks

rot13 assert problem

---

students/pei/session04/kata14.py
students/pei/session04/sherlocksmall.txt

Did the home work...but my code didn't get to break out of the while loop, it raised an error: 
TypeError: object of type 'NoneType' has no len()
for this line of code: new += " " + ''.join(random.choice(grouping2.get(strLastTwo)))
So I added an exception, but then it never got to break out of the while loop. I don't know if that's alright...
Pei

added kata14 code

---

students/gabriel_meringolo/session_04/trigram.py

It looks like I was improving this as you were checking the old version. I feel like there might be a bit of redundancy in the formatting but besides that it should be good.

Trigram v 2.0

---

students/gabriel_meringolo/session_05/exceptions_lab.py

Made a safe_input wrapper with exceptions for input.
Not sure what IBAFP is for second part of lab..

working exception lab first part

---

students/ryan_morin/session_04/Lab.py
students/ryan_morin/session_04/kata14.py

Add kata14.py

---

students/gabriel_meringolo/session_05/dict_list_lab2.py
students/gabriel_meringolo/session_05/list_comp_lab.py

I completed the first part of this lab, but I think I'm overlooking something big or I may just be misunderstanding the instructions..
The code is simple and clean and gets the job done but I feel like I should be able to do it with dict comprehension instead of explicitly calling on the keys. That also leads me to believe that that would over complicate the code.. 
edit: I did the list comp and the dict comp parts as well. I'm not really sure how to create a dict using list comprehension. I ended up using zip on two lists that I created with list comprehension. hopefully I didn't miss the point of the assignment.

Dict list lab V2.x

---

students/ryan_morin/session_02/list_lab.py
students/ryan_morin/session_02/print_grid.py
students/ryan_morin/session_03/input_lab.py
students/ryan_morin/session_03/slicing.py
students/ryan_morin/session_03/str_formatting_lab.py
students/ryan_morin/session_04/dictionary_set_lab.py
students/ryan_morin/session_05/dict_set_comp_lab.py
students/ryan_morin/session_05/exceptions_lab.py
students/ryan_morin/session_05/first_last6.py
students/ryan_morin/session_05/string_times.py
students/ryan_morin/session_05/test_first_last6.py
students/ryan_morin/session_05/test_string_times.py
students/ryan_morin/session_06/lab_args_kwargs.py
students/ryan_morin/session_06/lam_key_magic_lab.py
students/ryan_morin/session_06/trapz.py
students/ryan_morin/session_07/html_render.py

Hello Chris and Maria
I've been getting acquainted with GitHub and haven't uploaded my stuff as regularly as I should. Feel free to not pay attention to work from previous weeks.
Regards,
Ryan

Updating directory with coding assignments

---

students/ericrosko/session03/mailroom.py
students/ericrosko/session04/dict_lab.py
students/ericrosko/session04/students.txt
students/ericrosko/session06/lambda_keyword.py
students/ericrosko/session06/positional-and-dictionary-arguments.py
students/ericrosko/session06/test_lambda.py
students/ericrosko/session07/html_render.py
students/ericrosko/session07/run_html_render.py
students/ericrosko/session07/test_html_render.py

Here is my partially done code for session 07 in case you want to view it during class.  It isn't done, but at least I'm halfway done through step 7.
I've also submitted the py.text file.  I'm not having problems, but I've been procrastinating a bit.

html session 07 assignment partially done

---

students/erica_winberry/session06/lambda_lab.py
students/erica_winberry/session06/test_trapz2.py
students/erica_winberry/session06/trapezoidal2.py
students/erica_winberry/session07/html_render.py
students/erica_winberry/session07/run_html_render.py
students/erica_winberry/session07/test_hr.py
students/erica_winberry/session07/test_html_output1.html
students/erica_winberry/session07/test_html_output2.html
students/erica_winberry/session07/test_html_output3.html
students/erica_winberry/session07/test_html_output4.html
students/erica_winberry/session07/test_html_output5.html
students/erica_winberry/session07/test_html_output6.html
students/erica_winberry/session07/test_html_output7.html
students/erica_winberry/session07/test_html_output8.html
students/erica_winberry/session08/circle_lab.py
students/erica_winberry/session08/test_circle.py

Not much to ask about. I got the renderer to work, for the most part.  Looking at the solution, my code looks very, very cluttered.

Homework, Week 7

---

students/gabriel_meringolo/session_07/html_render.py
students/gabriel_meringolo/session_08/circle.py
students/gabriel_meringolo/session_08/test_circle.py

I completed the main part of the lab with the appropriate tests.

circle lab with tests.

---

students/gabriel_meringolo/session_08/sparse_array.py
students/gabriel_meringolo/session_08/test_sparse_array.py

I've added the len() fun to the SparseArray class but I'm conflicted on the direction I should proceed from here...
The idea behind the exercise is to create a special class thats helps conserve memory when dealing with sparse arrays by removing the zeros. Would keeping the original sparse array around so it can be used for the len() fun defeat the purpose of the lab? or would creating a len var that increases every time a number is added ;regardless if a zero or not; be a better route?

sparse array 

---

students/ryan_morin/session_08/Circle.py
students/ryan_morin/session_08/quadratic_lab
students/ryan_morin/session_08/quadratic_lab.py
students/ryan_morin/session_08/test_Circle.py

The in class labs.  I'm still working on the circle lab.

In class labs

---

students/erica_winberry/session08/circle_lab.py
students/erica_winberry/session08/test_circle.py

(In circle_lab.py and test_circle.py) I've written __str__ and __repr__ methods, and they work properly, but my test fails. Not sure what I'm doing wrong. Am I missing something?

Step 6 of circle lab question

---

students/ryan_morin/session_09/iterateme.py

Upload class lab

---

students/ryan_morin/final_project/mortgage.py
students/ryan_morin/final_project/pv_mortgage.py

This is the first attempt at the final project. I'm working on a different version using pandas.

Final project first attempt

---

students/ryan_morin/final_project/mortgage.py
students/ryan_morin/final_project/mtgcalc.py

Hey Chris
I've been tinkering with pandas. I can get the program to work... kinda. I'm having trouble with the loop on line 205. The program picks up the last mortgage in the CSV file and calculates it's cash flow. I intended it to loop through all the mortgages. I'm guessing that my indentation is wrong but it could just as easily be something else.
Thanks Chris I enjoyed your class.

New approach to final project
